project_shelby/app/urls.py
from django.conf.urls import url
from .views import *

app_name = 'portal'

urlpatterns = [
    url(r'^$', RSVCreateView.as_view(), name='dashboard'),
    url('/', RSVListView.as_view(), name='attendees'),
]

project_shelby/config/urls.py
from django.conf.urls import url, include, handler404
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls')),
]

project_shelby/app/models.py
from django.db import models

class Attendee(models.Model):
    fb_username = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    contact_number = models.CharField(max_length=60)

    

project_shelby/app/forms.py
from django import forms
from django.db.models import Q

from app.models import Attendee
from app.utils.api import ApiClient

api = ApiClient()

class AttendeeForm(forms.ModelForm):
    class Meta:
        model= Attendee
        fields = '__all__'

    def save(self, *args, **kwargs):
        attendee = super().save(commit=False)
        attendee.name = attendee.name.upper()
        fb_username =  attendee.fb_username
        contact_number = attendee.contact_number
        query = Attendee.objects.filter(Q(fb_username=fb_username) | Q(contact_number=contact_number))
        
        if not query:
            attendee.save()
  
        # data = {}
        # data['address'] = contact_number
        # data['name'] = attendee.name
        # resp = api.send_sms(data)
        # print('response', resp)

project_shelby/app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse
from django.views.generic import FormView
from django.views.generic.edit import CreateView
from django.views.generic import ListView
from django.db.models import Q
from app.models import Attendee

from app.forms import *
from app.models import *


class RSVCreateView(CreateView):
    template_name = 'index.html'
    form_class = AttendeeForm

    def get_success_url(self):
        return reverse('portal:attendees')

class RSVListView(ListView):
    template_name = 'attendees.html'

    def get_queryset(self):
        queryset = Attendee.objects.filter()
        return queryset

project_shelby/app/templates/attendees.html
{% load staticfiles %}
<!DOCTYPE html>
 <html class="no-js">
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Shelby Jaelle's Christening and 1st Birthday</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Shelby Jaelle Christening and Birthday" />

	<link rel="icon" type="image/png" href="https://upload.wikimedia.org/wikipedia/commons/7/73/STC_line_1_icon.png">


	<link href='https://fonts.googleapis.com/css?family=Work+Sans:400,300,600,400italic,700' rel='stylesheet' type='text/css'>
	<link href="https://fonts.googleapis.com/css?family=Sacramento" rel="stylesheet">
	
	<link href="https://fonts.googleapis.com/css?family=Sigmar+One&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Caveat+Brush&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>


	</head>
	<body>
		
	
	<div id="page">


    <div id="fh5co-couple-story" style=" margin-top: 0; height: 80vh;">
		<div class="container">
			<div class="row">
				<div class="col-md-10 col-md-offset-1 text-center fh5co-heading animate-box">
					<!-- <span>Shelby Jaelle's</span> -->
					<h2>Attendees</h2>
				</div>
			</div>
			<div class="row animate-box">
				
				<div class="col-md-10 col-md-offset-1">
					{% for attendee in object_list %}
						<div class="col-md-4 col-sm-4">
							<ul class="timeline" style="padding:0;">
								<li>
									<h5 class="text-uppercase attendees" style="color:#828282;">{{ attendee.name }}</h5>
								</li>
							</ul>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>
    </div>
    <div>
        <div class="row">
            <div class="col-md-4 col-sm-4" style="padding:0;">
                <img class="animate-box" src="{% static 'img/o.jpg'%}" width="100%">
            </div>
            <div class="col-md-4 col-sm-4" style="padding:0;">
                <img class="animate-box" src="{% static 'img/n.jpg'%}" width="100%">
            </div>
            <div class="col-md-4 col-sm-4" style="padding:0;">
                <img class="animate-box" src="{% static 'img/e.jpg'%}" width="100%">
            </div>
        </div>
    </div>
	
	



	




	<footer id="fh5co-footer" role="contentinfo">
		<div class="container">

			<div class="row copyright">
				<div class="col-md-12 text-center">
					<p>
						<small class="block"><strong><a href="{% url 'portal:dashboard' %}">Project Shelby</a></strong> &copy; 2019 All Rights Reserved.</small> 
					</p>
					
				</div>
			</div>

		</div>
	</footer>
	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>
	
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/jquery.countTo.js' %}"></script>
	<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/magnific-popup-options.js' %}"></script>

	<script src="{% static 'js/simplyCountdown.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

	
	<script>
        var timer = setTimeout(function() {
            window.location= "{% url 'portal:dashboard'%}"
        }, 8000);
    </script>
	</body>
</html>

project_shelby/app/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
 <html class="no-js">
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Shelby Jaelle's Christening and 1st Birthday</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Shelby Jaelle Christening and Birthday" />
	
	<link rel="icon" type="image/png" href="https://upload.wikimedia.org/wikipedia/commons/7/73/STC_line_1_icon.png">

	<link href='https://fonts.googleapis.com/css?family=Work+Sans:400,300,600,400italic,700' rel='stylesheet' type='text/css'>
	<link href="https://fonts.googleapis.com/css?family=Sacramento" rel="stylesheet">
	
	<link href="https://fonts.googleapis.com/css?family=Sigmar+One&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Caveat+Brush&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>


	</head>
	<body>
		
	
	<div id="page">
	

	<header id="fh5co-header" class="fh5co-cover" role="banner" data-stellar-background-ratio="0.5" style="background-image: url({% static 'img/bg-1.jpeg' %});">
		<div class="overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-md-10 col-md-offset-1 text-center">
					<div class="display-t">
						<div class="display-tc animate-box" data-animate-effect="fadeIn">
							<h2 class="text-uppercase" style="font-weight: 600;">Join us to celebrate</h2>
							<h1>Shelby Jaelle's</h1>

							<h3 class="text-uppercase" style="margin-bottom: 0px; margin-top: 20px; text-shadow: 3px 3px 10px #F14E95;">Christening</h3>
								<span style="text-shadow: 3px 3px 10px #F14E95;">&nbspand&nbsp</span>
							<h3 class="text-uppercase" style="text-shadow: 3px 3px 10px #F14E95;">1st Birthday</h3>

							<h2 style="font-weight:600; text-shadow: 2px 2px 10px #F14E95;">Sunday 13th October 2019 At 10:00AM <br> 
								Holy Cross Parish Church Alcala <br> 
								Reception to follow at 11:00AM <br> 
								#101 National Rd., San Juan, Alcala, Pangasinan 2425</h2>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>

	<div id="fh5co-event" class="fh5co-bg" style="background-image: url(https://free4kwallpapers.com/uploads/originals/2015/07/18/pink-background-designs.jpg); background-repeat: no-repeat; background-attachment: fixed; background-size:">
		<div class="overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading animate-box">
					<h2>The Godparents</h2>
				</div>
			</div>
			<div class="row">
				<div class="display-t">
					<div class="display-tc">
						<div class="col-md-10 col-md-offset-1">
							<div class="col-md-6 col-sm-6 text-center">
								<div class="event-wrap animate-box">
									<div class="col-12 gp-zoom">
										<span class="nic">Nicole Anne Lanuza</span>
										<span class="alo">Angelou De leon</span>
										<span class="san">Maria Sandryl Musni</span>
										<span class="and">Andrei Julianne Libed</span>
										<span class="gra">Mary Grace Tumala</span>
										<span class="may">Nica May Tropia</span>
										<span class="lia">Lia Jalaine De Guzman</span>
										<span class="mar">Mariel Lucas</span>
										<span class="ang">Maria Angela Laglagura</span>
										<span class="mau">Maureen Carmelo</span>
										<span class="mau">Jennalyn Soriano</span>
									</div>
									
								</div>
							</div>
							<div class="col-md-6 col-sm-6 text-center">
								<div class="event-wrap animate-box">
									<div class="col-12 gp-zoom">
										<span class="chr">Mark Christian Custodio</span>
										<span class="vin">Vince Lorde Marquez</span>
										<span class="bry">Bryan Lloyd Queyquep</span>
										<span class="den">Denzel Andaya</span>
										<span class="arn">Arnold Dacanay</span>
										<span class="ian">Dan Ian Ismael Senen</span>
										<span class="ern">Ernie Melendez</span>
										<span class="ant">Mark Anthony Marcial</span>
										<span class="eds">Edwin Santos</span>
										<span class="ste">Adonis Dave Jacob</span>
										<span class="van">Ivan Kenneth Soriano</span>

									</div>
									
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	

	<div id="fh5co-couple-story" style=" margin-top: 0; ">
		<div class="container">
			<div class="row">
				<div class="col-md-10 col-md-offset-1 text-center fh5co-heading animate-box">
					<!-- <span>Shelby Jaelle's</span> -->
					<h2>My First Year</h2>
					<p>October 13, 2018 - October 13, 2019</p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-3 col-sm-4">
					<ul class="timeline animate-box">
						<li class="animate-box">
							<div class="text-center box-shadow">
								<img class="photos" src="{% static 'img/sh-0.jpg' %}">
								<h4 class="photos-title text-uppercase">Newborn</h4>
							</div>
						</li>
			    	</ul>
				</div>
				<div class="col-md-3 col-sm-4">
					<ul class="timeline animate-box">
						<li class="animate-box">
							<div class="text-center box-shadow">
								<img class="photos" src="{% static 'img/sh-1.jpg' %}">
								<h4 class="photos-title text-uppercase">1 Month</h4>
							</div>
						</li>
			    	</ul>
				</div>
				<div class="col-md-3 col-sm-4">
					<ul class="timeline animate-box">
						<li class="animate-box">
							<div class="text-center box-shadow">
								<img class="photos" src="{% static 'img/sh-2.jpg' %}">
								<h4 class="photos-title text-uppercase">2 Months</h4>
							</div>
						</li>
			    	</ul>
				</div>
				<div class="col-md-3 col-sm-4">
					<ul class="timeline animate-box">
						<li class="animate-box">
							<div class="text-center box-shadow">
								<img class="photos" src="{% static 'img/sh-3.jpg' %}">
								<h4 class="photos-title text-uppercase">3 Months</h4>
							</div>
						</li>
			    	</ul>
				</div>
				<div class="col-md-3 col-sm-4">
					<ul class="timeline animate-box">
						<li class="animate-box">
							<div class="text-center box-shadow">
								<img class="photos" src="{% static 'img/sh-4.jpg' %}">
								<h4 class="photos-title text-uppercase">4 Months</h4>
							</div>
						</li>
			    	</ul>
				</div>
				<div class="col-md-3 col-sm-4">
					<ul class="timeline animate-box">
						<li class="animate-box">
							<div class="text-center box-shadow">
								<img class="photos" src="{% static 'img/sh-5.jpg' %}">
								<h4 class="photos-title text-uppercase">5 Months</h4>
							</div>
						</li>
			    	</ul>
				</div>
				<div class="col-md-3 col-sm-4">
					<ul class="timeline animate-box">
						<li class="animate-box">
							<div class="text-center box-shadow">
								<img class="photos" src="{% static 'img/sh-6.jpg' %}">
								<h4 class="photos-title text-uppercase">6 Months</h4>
							</div>
						</li>
			    	</ul>
				</div>
				<div class="col-md-3 col-sm-4">
					<ul class="timeline animate-box">
						<li class="animate-box">
							<div class="text-center box-shadow">
								<img class="photos" src="{% static 'img/sh-7.jpg' %}">
								<h4 class="photos-title text-uppercase">7 Months</h4>
							</div>
						</li>
			    	</ul>
				</div>
				<div class="col-md-3 col-sm-4">
					<ul class="timeline animate-box">
						<li class="animate-box">
							<div class="text-center box-shadow">
								<img class="photos" src="{% static 'img/sh-8.jpg' %}">
								<h4 class="photos-title text-uppercase">8 Months</h4>
							</div>
						</li>
			    	</ul>
				</div>
				<div class="col-md-3 col-sm-4">
					<ul class="timeline animate-box">
						<li class="animate-box">
							<div class="text-center box-shadow">
								<img class="photos" src="{% static 'img/sh-9.jpg' %}">
								<h4 class="photos-title text-uppercase">9 Months</h4>
							</div>
						</li>
			    	</ul>
				</div>
				<div class="col-md-3 col-sm-4">
					<ul class="timeline animate-box">
						<li class="animate-box">
							<div class="text-center box-shadow">
								<img class="photos" src="{% static 'img/sh-10.jpg' %}">
								<h4 class="photos-title text-uppercase">10 Months</h4>
							</div>
						</li>
			    	</ul>
				</div>
				<div class="col-md-3 col-sm-4">
					<ul class="timeline animate-box">
						<li class="animate-box">
							<div class="text-center box-shadow">
								<img class="photos" src="{% static 'img/sh-11.jpg' %}">
								<h4 class="photos-title text-uppercase">11 Months</h4>
							</div>
						</li>
			    	</ul>
				</div>
			</div>
		</div>
	</div>
	

	


	<div id="fh5co-started" class="fh5co-bg" style="background-image: url(https://free4kwallpapers.com/uploads/originals/2015/07/18/pink-background-designs.jpg); background-repeat: no-repeat; background-attachment: fixed; background-size: cover;">
		<div class="overlay"></div>
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
					<h2>Are You Attending?</h2>
					<p style="color:#828282;">Please Fill-up the form to confirm that you're attending. Thanks!</p>
				</div>
			</div>
			<div class="row animate-box">
				<div class="col-md-12">
					<form class="form-inline" method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						<div class="col-md-3 col-sm-12">
							<div class="form-group">
								<!-- <label for="name" class="sr-only">Name</label> -->
								<input type="name" class="form-control" id="name" placeholder="Name" name="{{form.name.name}}" value="{{form.name.value|default:""}}" required>
							</div>
						</div>
						<div class="col-md-3 col-sm-12">
							<div class="form-group">
								<!-- <label for="mobile" class="sr-only">Mobile No.</label> -->
								<input type="mobile" class="form-control" id="Mobile" placeholder="Mobile No. (097xxxxxxxx)" name="{{form.contact_number.name}}" value="{{form.contact_number.value|default:""}}" required>
							</div>
						</div>
						<div class="col-md-3 col-sm-12">
							<div class="form-group">
								<!-- <label for="email" class="sr-only">Email</label> -->
								<input type="name" class="form-control" id="email" placeholder="FB username" name="{{form.fb_username.name}}" value="{{form.fb_username.value|default:""}}" required>
							</div>
						</div>
						<div class="col-md-3 col-sm-12">
							<button type="submit" class="btn btn-default btn-block">I am Attending</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

	<footer id="fh5co-footer" role="contentinfo">
		<div class="container">

			<div class="row copyright">
				<div class="col-md-12 text-center">
					<p>
						<small class="block"><strong><a href="{% url 'portal:dashboard' %}">Project Shelby</a></strong> &copy; 2019 All Rights Reserved.</small> 
					</p>
					
				</div>
			</div>

		</div>
	</footer>
	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>
	
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/jquery.countTo.js' %}"></script>
	<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/magnific-popup-options.js' %}"></script>

	<script src="{% static 'js/simplyCountdown.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

	<script>
    var d = new Date(new Date().getTime() + 200 * 120 * 120 * 2000);

    // default example
    simplyCountdown('.simply-countdown-one', {
        year: d.getFullYear(),
        month: d.getMonth() + 1,
        day: d.getDate()
    });

    //jQuery example
    $('#simply-countdown-losange').simplyCountdown({
        year: d.getFullYear(),
        month: d.getMonth() + 1,
        day: d.getDate(),
        enableUtc: false
    });
</script>

	</body>
</html>